# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'siriIntent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for siriIntent

end

target 'siriIntentUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for siriIntentUI

end

target 'sirikit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sirikit

end
